//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeKnow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationInfo
    {
        public int EducationInfoID { get; set; }
        public Nullable<int> UseID { get; set; }
        public Nullable<int> EducationTypeID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> SchoolFacultyID { get; set; }
        public Nullable<System.DateTime> EnterDateTime { get; set; }
    }
}
