//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeKnow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfessionInfo
    {
        public int ProfessionInfoID { get; set; }
        public int UseID { get; set; }
        public string ProfessionName { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public string BranchPosition { get; set; }
    }
}
