//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeKnow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublishInfo
    {
        public int Pu_ID { get; set; }
        public Nullable<int> UseID { get; set; }
        public string Pu_Content { get; set; }
        public Nullable<System.DateTime> Pu_Date { get; set; }
        public Nullable<int> PublishTypeID { get; set; }
        public Nullable<int> TransmitID { get; set; }
    }
}
