//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeKnow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserNick { get; set; }
        public string UserReallyName { get; set; }
        public string UserImgs { get; set; }
        public string UserPwd { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<System.DateTime> Brithday { get; set; }
        public Nullable<int> QQ { get; set; }
        public string InterAdress { get; set; }
        public string UserDesc { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<int> Sexid { get; set; }
        public string Summary { get; set; }
        public Nullable<int> Statck { get; set; }
    }
}
