//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeKnow.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeizhiModel : DbContext
    {
        public WeizhiModel()
            : base("name=WeizhiModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Area> Area { get; set; }
        public DbSet<Attention> Attention { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<Collect> Collect { get; set; }
        public DbSet<Comment> Comment { get; set; }
        public DbSet<EducationInfo> EducationInfo { get; set; }
        public DbSet<EducationType> EducationType { get; set; }
        public DbSet<ProfessionInfo> ProfessionInfo { get; set; }
        public DbSet<Province> Province { get; set; }
        public DbSet<PublishInfo> PublishInfo { get; set; }
        public DbSet<PublishType> PublishType { get; set; }
        public DbSet<SchoolFaculty> SchoolFaculty { get; set; }
        public DbSet<SchoolInfo> SchoolInfo { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
    }
}
